[Content] STFT Overview
flucoma/learn-website pull request #137
Opened 2022-01-04 11:51 UTC by jamesb93

2022-01-12 15:42 UTC, tremblap requested changes
Again I recognise material. I think we should use material like I did in Utrecht (as well with what is there) to show more graphically the uncertainty (large window having both a snare and a bass drum is always impactful) and the linearity issues (drawing in octaves in lin, and annotating with nbBinsperOctave in a log graph) - musicians 'get' that. we could even play smearing examples.

the section of phase vocoding we could probably remove I think. otherwise I think the rest has everything we need

2022-01-12 16:01 UTC, weefuzzy commented on src/routes/overviews/stft.svx
> +Note that this is not the same as getting a more precise analysis from the same window: the constraint on how close together in frequency things can be distinguished is governed still by the size of
'Note that' starts two paragraphs.

2022-01-12 16:03 UTC, weefuzzy commented
Not sure I'm up for getting rid of the PV section, given that its associated mental model is a source of much wishful thinking about what STFTs can achieve. If we want to explain that the assumption that a Fourier domain representation can only be conceived in terms of components that have analysable frequencies under some specific conditions, how else would we do it?

2022-01-12 16:59 UTC, jamesb93 commented on src/routes/overviews/stft.svx
> +# Resources
Yeah, I like your approach in the original learn with "cards". I'm just a lazy bones and haven't gotten around to making a component that I think looks good and communicates well. I've made an issue internally to do so.

2022-01-12 19:05 UTC, jamesb93 commented on src/routes/overviews/stft.svx
> +# Resources
Does this look good to you @weefuzzy https://github.com/flucoma/learn-website/pull/158 (check the chroma reference on this PR).

2022-01-12 20:01 UTC, tedmoore commented
I am not sure who the intended reader of this is. In general I think it's too jargon-y. There are assumptions being made that I'm not sure we can or should make. I think a chat about the intended readership and the goals of this page would help me get a better sense of what to be considering as I read.

2022-01-12 21:29 UTC, jamesb93 commented
> I am not sure who the intended reader of this is. In general I think it's too jargon-y. There are assumptions being made that I'm not sure we can or should make. I think a chat about the intended readership and the goals of this page would help me get a better sense of what to be considering as I read.

I think I should remind all reviewers that this is old learn content extracted from Owen's initial putting together of the learn platform. Obviously what we (the new additions) know, the team and almost every circumstance of the project has changed since then, so these have been put up as a sort of stimulus for us to discuss what we might envisage an STFT article to look like now. Certainly our collective attempts to explain the STFT in workshops should influence this (PAs explanation was good and draws on easily understandable examples + metaphors), as well what how we think an STFT primer will support the entangled sprawl of resources we offer. In that light I think we should focus on what we think is valuable, how it can be extended, and what we think can be either removed or perhaps further distilled. I'm not convinced its that jargony if we were to aim it somewhere in the middleground rather than at an absolute beginner. Perhaps glossing over certain concepts (like the distinction between a DFT/FFT) might be valuable to focus the discussion on the way this particular decomposition model influences other things (pitch analysis and minimum frequencies for example). Again, we don't want to reinvent the wheel as there are already tonnes of good splainers out there, like the Jack Schaedler one for example.

2022-01-12 22:03 UTC, weefuzzy commented
Thanks for the shielding @jamesb93 😆 

To answer Ted's question, all the techno arcana was there because I was trying to address the problem (or maybe not-problem) that folk in our field 'know' stuff about spectral processing that they've digested by rote, and not knowing where it comes from (I think) gets in the way of being able to properly screw around with stuff. E.g why the powers-of-two thing? It's a condition of the FFTs algorithm design, nothing to do with DFTs. Why distinguish between an STFT and the rest of it? Because that's where challenges with window leakage, overlap add, space monkeys and so forth come in. 

I guess I was pitching for something that bridges the lovely, but still over simplified account in Wishart's _Audible Design_, and the equally lovely but starting to get a bit techy account in Lyon's _Understanding DSP_, or even the Circles, Sines and Signals site.

2022-01-12 22:14 UTC, jamesb93 commented
> Thanks for the shielding @jamesb93 😆

I know you're a big boy but it is probably non-obvious to Ted the origin of this material which is useful context.

> To answer Ted's question, all the techno arcana was there because I was trying to address the problem (or maybe not-problem) that folk in our field 'know' stuff about spectral processing that they've digested by rote, and not knowing where it comes from (I think) gets in the way of being able to properly screw around with stuff. E.g why the powers-of-two thing? It's a condition of the FFTs algorithm design, nothing to do with DFTs. Why distinguish between an STFT and the rest of it? Because that's where challenges with window leakage, overlap add, space monkeys and so forth come in.
> 
> I guess I was pitching for something that bridges the lovely, but still over simplified account in Wishart's _Audible Design_, and the equally lovely but starting to get a bit techy account in Lyon's _Understanding DSP_, or even the Circles, Sines and Signals site.

Maybe something useful to draw up would be the take home messages we want to instill in this article using those external resources to cover our own gaps and to focus on the things that are perhaps most relevant to our objects (and relying on them as ways of explaining things too).

2022-01-12 22:37 UTC, tedmoore commented
Cool. I do like the idea of having a page that gets at those myths and things we learned by rote. I think it could even be titled that way. "Things often misunderstood about FFT". Or something less negative perhaps.

2022-01-12 22:41 UTC, jamesb93 commented
I set my window to something other than a power of two you won’t guess what happened next?

> On 12 Jan 2022, at 22:37, Ted Moore ***@***.***> wrote:
> 
> 
> Cool. I do like the idea of having a page that gets at those myths and things we learned by rote. I think it could even be titled that way. "Things often misunderstood about FFT". Or something less negative perhaps.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/flucoma/learn-website/pull/137#issuecomment-1011513839>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ADFKURS7A3PRI6GMYGH5DL3UVX7DBANCNFSM5LHIQFPA>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
> You are receiving this because you were mentioned.
>

2022-03-06 18:04 UTC, tremblap commented
I think we can unfold. Our discussion about magnitude shows that musicians arrive from a practical perspective with a few assumptions and functional understanding which we can complement softly and not pratronisingly.

section 1: the essential (what i explained in Utrecht)

section 2: a few myth busters (what is in there now)

section 3: further reading for the math savvy (with links to sexy explanations)

(btw @tedmoore I'm still looking for my Lyon book - @jamesb93 I didn't lend it to you by any chance?)

2022-06-07 15:33 UTC, closed without merging