initial commit
flucoma/learn-website pull request #221
Opened 2022-02-16 14:41 UTC by tedmoore

2022-02-16 15:55 UTC, jamesb93 requested changes
The graphics could be made slightly easier to read by making any lines thicker. I'd twice as thick if it doesn't obscure them but anywhere between what they are now and double would be great. Otherwise its all very very clear.

2022-02-16 15:55 UTC, jamesb93 commented on src/routes/learn/seeding-nmf.svx
> +Non-negative matrix factorisation can be "seeded," meaning that it is given some information to begin the process from. You can provide bases and/or activations that you think will "point the algorit
I would remind them of the process, even a key word like "decomposition" might be helpful here

2022-02-28 12:50 UTC, merged

2022-03-06 17:41 UTC, tremblap commented
too late for review it seems but this is fantastic! It gets a bit jargony but hey, it is quite something. I think that the oversampling bundling of the guitar is still missing as one last example though, as a form of synthesis of machine listening to sieve.

2022-03-07 08:18 UTC, tremblap commented
also there is a white lie in there - as it is merged I'll do a bug report